---
####
####
- hosts: "{{ hosts_inventory }}"
  max_fail_percentage: 0
  serial: 1
  become: yes

  roles:
#  - stop-applications
    - ansible_os_update
#  - server-config-xyz
#  - start-applications
