---
- hosts: "{{ hosts_inventory }}"
  become: yes

  tasks:
   - name: Check the uptime prior reboot
     shell: uptime
     register: UPTIME_PRE_REBOOT

   - debug: msg={{UPTIME_PRE_REBOOT.stdout}}

   - name: Reboot node and stop polling.
     shell: sleep 5 && shutdown -r now  "This system is going for reboot now."
     ignore_errors: true
     async: 10 # Do not care for 10 sec
     poll: 0 # Fire & Forget

   - name: wait for reboot to complete and SSH to become available 
     wait_for_connection:
       timeout: 600
       dalay: 60
     when: reboot_default | bool and reboot_hint_result | bool

 name: Check the uptime post reboot
     shell: uptime
     register: UPTIME_POST_REBOOT

   - debug: msg={{UPTIME_POST_REBOOT.stdout}}
